"""Initial migration

Revision ID: 94ababa377c8
Revises: d5a46c03bd9f
Create Date: 2025-03-11 06:16:20.952442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ababa377c8'
down_revision = 'd5a46c03bd9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
